import type {
  InvoiceMetadata,
  SubscriptionPlan,
  SupportGrant,
  TenantSubscription,
} from "./types";

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: "plan-starter",
    code: "STARTER",
    name: "Starter",
    description: "Gói khởi tạo cho doanh nghiệp nhỏ cần HR core và onboarding cơ bản.",
    monthlyPriceVnd: 3900000,
    storageLimitGb: 80,
    adminSeatLimit: 3,
    employeeSeatLimit: 60,
    supportSla: "8x5, phản hồi trong 1 ngày làm việc",
    modules: ["Nhân sự", "Hồ sơ", "Chấm công"],
    highlight: "Nhanh triển khai",
  },
  {
    id: "plan-growth",
    code: "GROWTH",
    name: "Growth",
    description: "Gói tăng trưởng cho công ty đang mở rộng chi nhánh và cần hợp đồng số.",
    monthlyPriceVnd: 8900000,
    storageLimitGb: 220,
    adminSeatLimit: 8,
    employeeSeatLimit: 250,
    supportSla: "8x5, phản hồi trong 4 giờ làm việc",
    modules: ["Nhân sự", "Chấm công", "Hợp đồng điện tử", "Phân quyền"],
    highlight: "Phổ biến nhất",
  },
  {
    id: "plan-scale",
    code: "SCALE",
    name: "Scale",
    description: "Gói cho doanh nghiệp nhiều pháp nhân cần quota lớn và audit rõ ràng.",
    monthlyPriceVnd: 16900000,
    storageLimitGb: 600,
    adminSeatLimit: 18,
    employeeSeatLimit: 1200,
    supportSla: "12x6, phản hồi trong 2 giờ làm việc",
    modules: ["Nhân sự", "Chấm công", "Hợp đồng", "Tài liệu", "Audit log"],
    highlight: "Đa chi nhánh",
  },
  {
    id: "plan-enterprise",
    code: "ENTERPRISE",
    name: "Enterprise",
    description: "Gói enterprise cho tenant cần chính sách riêng, SLA riêng và quota tùy biến.",
    monthlyPriceVnd: 32500000,
    storageLimitGb: 1500,
    adminSeatLimit: 50,
    employeeSeatLimit: 5000,
    supportSla: "24x7, kiến trúc riêng theo hợp đồng",
    modules: ["Tất cả phân hệ", "SSO", "Audit nâng cao", "Support ticket có kiểm soát"],
    highlight: "Tùy chỉnh theo hợp đồng",
  },
];

export const initialTenants: TenantSubscription[] = [
  {
    id: "tenant-an-phat",
    companyName: "Công ty CP An Phát Logistics",
    workspaceCode: "ANPHAT",
    subscriptionCode: "SUB-ANPHAT-2026",
    planCode: "GROWTH",
    planName: "Growth",
    subscriptionStatus: "active",
    onboardingStatus: "ready",
    billingCycle: "monthly",
    nextRenewalAt: "2026-05-01T00:00:00.000Z",
    portalAdminEmail: "admin@anphatlogistics.vn",
    storageLimitGb: 220,
    storageUsedGb: 164,
    adminSeats: 5,
    activeEmployees: 142,
    lastInvoiceCode: "INV-ANPHAT-2026-04",
    billingStatus: "paid",
    workspaceIsolationMode: "ticket-only-support",
    supportAccessStatus: "not_requested",
  },
  {
    id: "tenant-minh-tam",
    companyName: "Minh Tâm Retail",
    workspaceCode: "MINHTAM",
    subscriptionCode: "SUB-MINHTAM-2026",
    planCode: "STARTER",
    planName: "Starter",
    subscriptionStatus: "trial",
    onboardingStatus: "trial",
    billingCycle: "monthly",
    nextRenewalAt: "2026-04-25T00:00:00.000Z",
    portalAdminEmail: "owner@minhtamretail.vn",
    storageLimitGb: 80,
    storageUsedGb: 29,
    adminSeats: 2,
    activeEmployees: 34,
    lastInvoiceCode: "INV-MINHTAM-TRIAL-01",
    billingStatus: "draft",
    workspaceIsolationMode: "ticket-only-support",
    supportAccessStatus: "pending_customer_approval",
    supportTicketId: "SUP-2418",
  },
  {
    id: "tenant-seafoods",
    companyName: "BlueSea Foods",
    workspaceCode: "BLUESEA",
    subscriptionCode: "SUB-BLUESEA-2025",
    planCode: "SCALE",
    planName: "Scale",
    subscriptionStatus: "past_due",
    onboardingStatus: "ready",
    billingCycle: "quarterly",
    nextRenewalAt: "2026-04-18T00:00:00.000Z",
    portalAdminEmail: "ops@blueseafoods.vn",
    storageLimitGb: 600,
    storageUsedGb: 541,
    adminSeats: 9,
    activeEmployees: 688,
    lastInvoiceCode: "INV-BLUESEA-2026-Q2",
    billingStatus: "overdue",
    workspaceIsolationMode: "ticket-only-support",
    supportAccessStatus: "granted",
    supportTicketId: "SUP-2391",
    supportAccessExpiresAt: "2026-04-15T17:00:00.000Z",
  },
  {
    id: "tenant-hoang-gia",
    companyName: "Hoàng Gia Hospitality",
    workspaceCode: "HOANGGIA",
    subscriptionCode: "SUB-HOANGGIA-2026",
    planCode: "ENTERPRISE",
    planName: "Enterprise",
    subscriptionStatus: "active",
    onboardingStatus: "setup_in_progress",
    billingCycle: "yearly",
    nextRenewalAt: "2026-11-30T00:00:00.000Z",
    portalAdminEmail: "cio@hoanggia.vn",
    storageLimitGb: 1500,
    storageUsedGb: 614,
    adminSeats: 16,
    activeEmployees: 1280,
    lastInvoiceCode: "INV-HOANGGIA-2026-Y1",
    billingStatus: "upcoming",
    workspaceIsolationMode: "ticket-only-support",
    supportAccessStatus: "not_requested",
  },
  {
    id: "tenant-sao-khue",
    companyName: "Sao Khuê Tech",
    workspaceCode: "SAOKHUE",
    subscriptionCode: "SUB-SAOKHUE-2024",
    planCode: "GROWTH",
    planName: "Growth",
    subscriptionStatus: "suspended",
    onboardingStatus: "awaiting_contract",
    billingCycle: "monthly",
    nextRenewalAt: "2026-04-10T00:00:00.000Z",
    portalAdminEmail: "finance@saokhue.tech",
    storageLimitGb: 220,
    storageUsedGb: 88,
    adminSeats: 4,
    activeEmployees: 96,
    lastInvoiceCode: "INV-SAOKHUE-2026-03",
    billingStatus: "overdue",
    workspaceIsolationMode: "ticket-only-support",
    supportAccessStatus: "expired",
    supportTicketId: "SUP-2280",
    supportAccessExpiresAt: "2026-03-29T18:00:00.000Z",
  },
];

export const invoiceMetadata: InvoiceMetadata[] = [
  {
    id: "invoice-1",
    invoiceCode: "INV-ANPHAT-2026-04",
    companyName: "Công ty CP An Phát Logistics",
    workspaceCode: "ANPHAT",
    billingPeriodLabel: "Tháng 04/2026",
    issuedAt: "2026-04-01T08:00:00.000Z",
    dueAt: "2026-04-07T17:00:00.000Z",
    amountVnd: 8900000,
    status: "paid",
    paymentGatewayRef: "PAY-9X2A-3141",
    summaryNote: "Metadata gói Growth + 2 admin seats bổ sung.",
    metadataScope: "service-metadata-only",
  },
  {
    id: "invoice-2",
    invoiceCode: "INV-BLUESEA-2026-Q2",
    companyName: "BlueSea Foods",
    workspaceCode: "BLUESEA",
    billingPeriodLabel: "Quý 2/2026",
    issuedAt: "2026-04-01T09:15:00.000Z",
    dueAt: "2026-04-12T17:00:00.000Z",
    amountVnd: 50700000,
    status: "overdue",
    paymentGatewayRef: "PAY-Q2X-8821",
    summaryNote: "Scale quarterly, chỉ lưu trạng thái dịch vụ và tổng tiền.",
    metadataScope: "service-metadata-only",
  },
  {
    id: "invoice-3",
    invoiceCode: "INV-HOANGGIA-2026-Y1",
    companyName: "Hoàng Gia Hospitality",
    workspaceCode: "HOANGGIA",
    billingPeriodLabel: "Chu kỳ năm 2026",
    issuedAt: "2026-03-30T03:30:00.000Z",
    dueAt: "2026-04-20T17:00:00.000Z",
    amountVnd: 390000000,
    status: "upcoming",
    paymentGatewayRef: "PAY-Y1H-4410",
    summaryNote: "Enterprise annual commitment, chưa đến hạn thanh toán.",
    metadataScope: "service-metadata-only",
  },
  {
    id: "invoice-4",
    invoiceCode: "INV-MINHTAM-TRIAL-01",
    companyName: "Minh Tâm Retail",
    workspaceCode: "MINHTAM",
    billingPeriodLabel: "Trial onboarding",
    issuedAt: "2026-04-12T02:00:00.000Z",
    dueAt: "2026-04-25T17:00:00.000Z",
    amountVnd: 0,
    status: "draft",
    paymentGatewayRef: "TRIAL-0001",
    summaryNote: "Bản ghi trial, chưa phát sinh hóa đơn chính thức.",
    metadataScope: "service-metadata-only",
  },
];

export const initialSupportGrants: SupportGrant[] = [
  {
    ticketId: "SUP-2391",
    companyName: "BlueSea Foods",
    workspaceCode: "BLUESEA",
    requestedScope: "Hỗ trợ kiểm tra lỗi đồng bộ hợp đồng điện tử.",
    customerApprovedAt: "2026-04-13T03:20:00.000Z",
    approvedByCustomerContact: "ops@blueseafoods.vn",
    status: "granted",
    expiresAt: "2026-04-15T17:00:00.000Z",
    note: "Chỉ mở tạm quyền hỗ trợ trong phạm vi ticket đã xác nhận.",
  },
  {
    ticketId: "SUP-2418",
    companyName: "Minh Tâm Retail",
    workspaceCode: "MINHTAM",
    requestedScope: "Yêu cầu hỗ trợ cấu hình tenant mới và rà soát quota trial.",
    status: "pending_customer_approval",
    note: "Khách hàng chưa xác nhận cấp quyền hỗ trợ. Không được truy cập workspace.",
  },
  {
    ticketId: "SUP-2422",
    companyName: "Công ty CP An Phát Logistics",
    workspaceCode: "ANPHAT",
    requestedScope: "Cần hỗ trợ mở rộng dung lượng lên 300 GB và kiểm tra quota lưu trữ.",
    customerApprovedAt: "2026-04-14T01:10:00.000Z",
    approvedByCustomerContact: "admin@anphatlogistics.vn",
    status: "pending_customer_approval",
    note: "Khách hàng đã phê duyệt, chờ SuperAdmin kích hoạt phiên hỗ trợ có thời hạn.",
  },
  {
    ticketId: "SUP-2280",
    companyName: "Sao Khuê Tech",
    workspaceCode: "SAOKHUE",
    requestedScope: "Rà soát thất bại đồng bộ dữ liệu tenant.",
    customerApprovedAt: "2026-03-27T08:30:00.000Z",
    approvedByCustomerContact: "finance@saokhue.tech",
    status: "expired",
    expiresAt: "2026-03-29T18:00:00.000Z",
    note: "Phiên hỗ trợ đã hết hạn và đã tự động khóa lại quyền truy cập.",
  },
];
