export type PortalTab = "tenants" | "plans" | "billing" | "support";
export type SubscriptionStatus = "trial" | "active" | "past_due" | "suspended";
export type SubscriptionPlanStatus = "active" | "hidden";
export type BillingStatus = "paid" | "upcoming" | "overdue" | "draft";
export type PaymentTransactionSource = "manual" | "gateway";
export type SupportAccessStatus =
  | "not_requested"
  | "pending_customer_approval"
  | "granted"
  | "expired"
  | "revoked";
export type OnboardingStatus =
  | "awaiting_contract"
  | "setup_in_progress"
  | "ready"
  | "trial";

export interface SubscriptionPlan {
  id: string;
  code: string;
  name: string;
  description: string;
  status: SubscriptionPlanStatus;
  monthlyPriceVnd: number;
  storageLimitGb: number;
  adminSeatLimit: number;
  employeeSeatLimit: number;
  supportSla: string;
  modules: string[];
  highlight?: string;
}

export interface TenantSubscription {
  id: string;
  companyName: string;
  workspaceCode: string;
  subscriptionCode: string;
  planCode: string;
  planName: string;
  subscriptionStatus: SubscriptionStatus;
  onboardingStatus: OnboardingStatus;
  billingCycle: "monthly" | "quarterly" | "yearly";
  nextRenewalAt: string;
  portalAdminEmail: string;
  storageLimitGb: number;
  storageUsedGb: number;
  adminSeats: number;
  activeEmployees: number;
  lastInvoiceCode: string;
  billingStatus: BillingStatus;
  workspaceIsolationMode: "ticket-only-support";
  supportTicketId?: string;
  supportAccessStatus: SupportAccessStatus;
  supportAccessExpiresAt?: string;
}

export interface InvoiceMetadata {
  id: string;
  invoiceCode: string;
  tenantId: string;
  companyName: string;
  workspaceCode: string;
  tenantOwnerEmail: string;
  planCode: string;
  billingCycle: TenantSubscription["billingCycle"];
  billingPeriodLabel: string;
  issuedAt: string;
  dueAt: string;
  autoGeneratedAt: string;
  draftLeadDays: number;
  amountVnd: number;
  baseAmountVnd: number;
  discountVnd: number;
  additionalSeatFeeVnd: number;
  status: BillingStatus;
  paymentGatewayRef?: string;
  paymentSource?: PaymentTransactionSource;
  emailSentAt?: string;
  reminderSentAt?: string;
  paidAt?: string;
  receivedAt?: string;
  gracePeriodDays: number;
  graceEndsAt?: string;
  pdfFileName: string;
  summaryNote: string;
  metadataScope: "service-metadata-only";
}

export interface SupportGrant {
  ticketId: string;
  tenantId?: string;
  companyName: string;
  workspaceCode: string;
  tenantOwnerEmail?: string;
  requestedAt?: string;
  requestedBy?: string;
  requestedDurationHours?: number;
  requestedScope: string;
  customerApprovedAt?: string;
  approvedByCustomerContact?: string;
  status: SupportAccessStatus;
  expiresAt?: string;
  activatedAt?: string;
  revokedAt?: string;
  lastNotifiedAt?: string;
  note: string;
  impersonationToken?: string;
  sessionLaunchUrl?: string;
  auditActorLabel?: string;
}
