using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ERP.Entities;
using ERP.Entities.Models.ControlPlane;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace ERP.API.Workers
{
    public class BillingAutomationWorker : BackgroundService
    {
        private readonly ILogger<BillingAutomationWorker> _logger;
        private readonly IServiceProvider _serviceProvider;
        private const int CheckIntervalMinutes = 60; // Chạy mỗi giờ

        public BillingAutomationWorker(ILogger<BillingAutomationWorker> _logger, IServiceProvider serviceProvider)
        {
            this._logger = _logger;
            _serviceProvider = serviceProvider;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            _logger.LogInformation("Billing Automation Worker is starting.");

            while (!stoppingToken.IsCancellationRequested)
            {
                try
                {
                    using (var scope = _serviceProvider.CreateScope())
                    {
                        var context = scope.ServiceProvider.GetRequiredService<AppDbContext>();
                        await ProcessBillingAutomationAsync(context, stoppingToken);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error occurred while processing billing automation.");
                }

                await Task.Delay(TimeSpan.FromMinutes(CheckIntervalMinutes), stoppingToken);
            }

            _logger.LogInformation("Billing Automation Worker is stopping.");
        }

        private async Task ProcessBillingAutomationAsync(AppDbContext context, CancellationToken stoppingToken)
        {
            var now = DateTime.UtcNow;

            // 1. Sinh hóa đơn nháp (Draft) cho các Tenant sắp đến hạn gia hạn
            await GenerateDraftInvoicesAsync(context, now, stoppingToken);

            // 2. Chuyển hóa đơn sang trạng thái Quá hạn (Overdue)
            await MarkOverdueInvoicesAsync(context, now, stoppingToken);

            // 3. Khóa quyền truy cập (Suspend) nếu quá thời gian ân hạn
            await SuspendOverdueTenantsAsync(context, now, stoppingToken);
        }

        private async Task GenerateDraftInvoicesAsync(AppDbContext context, DateTime now, CancellationToken stoppingToken)
        {
            // LeadDays mặc định là 7 ngày
            var subscriptions = await context.TenantSubscriptions
                .Include(s => s.Plan)
                .Include(s => s.Tenant)
                .IgnoreQueryFilters()
                .Where(s => s.NextRenewalAt <= now.AddDays(7) && s.Status != "suspended")
                .ToListAsync(stoppingToken);

            foreach (var sub in subscriptions)
            {
                // Kiểm tra xem đã có hóa đơn nháp hoặc sắp tới cho kỳ này chưa
                var periodLabel = $"{sub.NextRenewalAt:MM/yyyy}";
                var exists = await context.InvoiceMetadata
                    .IgnoreQueryFilters()
                    .AnyAsync(inv => inv.TenantId == sub.TenantId && inv.BillingPeriodLabel == periodLabel, stoppingToken);

                if (!exists && sub.Plan != null)
                {
                    var invoice = new InvoiceMetadata
                    {
                        InvoiceCode = $"INV-{sub.Tenant.code}-{DateTime.UtcNow:yyMMddHHmm}",
                        TenantId = sub.TenantId,
                        WorkspaceCode = sub.Tenant.code,
                        BillingPeriodLabel = periodLabel,
                        BillingCycle = sub.BillingCycle,
                        BaseAmountVnd = sub.Plan.MonthlyPriceVnd,
                        AmountVnd = sub.Plan.MonthlyPriceVnd, // Sau này có thể cộng thêm phí seat phát sinh
                        Status = "draft",
                        IssuedAt = now,
                        DueAt = sub.NextRenewalAt,
                        AutoGeneratedAt = now,
                        GracePeriodDays = 7,
                        CreatedAt = now
                    };

                    await context.InvoiceMetadata.AddAsync(invoice, stoppingToken);
                    _logger.LogInformation("Generated draft invoice {InvoiceCode} for Tenant {TenantCode}", invoice.InvoiceCode, sub.Tenant.code);
                }
            }

            await context.SaveChangesAsync(stoppingToken);
        }

        private async Task MarkOverdueInvoicesAsync(AppDbContext context, DateTime now, CancellationToken stoppingToken)
        {
            var upcomingInvoices = await context.InvoiceMetadata
                .IgnoreQueryFilters()
                .Where(inv => inv.Status == "upcoming" && inv.DueAt < now)
                .ToListAsync(stoppingToken);

            foreach (var inv in upcomingInvoices)
            {
                inv.Status = "overdue";
                inv.GraceEndsAt = inv.DueAt.AddDays(inv.GracePeriodDays);
                inv.UpdatedAt = now;

                // Cập nhật BillingStatus trong subscription
                var sub = await context.TenantSubscriptions
                    .IgnoreQueryFilters()
                    .FirstOrDefaultAsync(s => s.TenantId == inv.TenantId, stoppingToken);
                if (sub != null)
                {
                    sub.BillingStatus = "overdue";
                }

                _logger.LogInformation("Invoice {InvoiceCode} marked as OVERDUE", inv.InvoiceCode);
            }

            await context.SaveChangesAsync(stoppingToken);
        }

        private async Task SuspendOverdueTenantsAsync(AppDbContext context, DateTime now, CancellationToken stoppingToken)
        {
            var overdueInvoices = await context.InvoiceMetadata
                .IgnoreQueryFilters()
                .Where(inv => inv.Status == "overdue" && inv.GraceEndsAt.HasValue && inv.GraceEndsAt.Value < now)
                .ToListAsync(stoppingToken);

            foreach (var inv in overdueInvoices)
            {
                var sub = await context.TenantSubscriptions
                    .IgnoreQueryFilters()
                    .Include(s => s.Tenant)
                    .FirstOrDefaultAsync(s => s.TenantId == inv.TenantId, stoppingToken);

                if (sub != null && sub.Status != "suspended")
                {
                    sub.Status = "suspended";
                    sub.UpdatedAt = now;
                    
                    if (sub.Tenant != null)
                    {
                        // Ghi log hoặc gửi notification ở đây
                        _logger.LogWarning("Tenant {TenantCode} SUSPENDED due to overdue payment of {InvoiceCode}", sub.Tenant.code, inv.InvoiceCode);
                    }
                }
            }

            await context.SaveChangesAsync(stoppingToken);
        }
    }
}
