using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.Entities.Models.ControlPlane
{
    [Table("Sys_InvoiceMetadata")]
    public class InvoiceMetadata
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string InvoiceCode { get; set; } = string.Empty;

        [Required]
        public int TenantId { get; set; }

        [Required]
        [StringLength(50)]
        public string WorkspaceCode { get; set; } = string.Empty;

        [Required]
        [StringLength(100)]
        public string BillingPeriodLabel { get; set; } = string.Empty;

        [Required]
        [StringLength(20)]
        public string BillingCycle { get; set; } = "monthly";

        [Column(TypeName = "decimal(18,2)")]
        public decimal AmountVnd { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal BaseAmountVnd { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal DiscountVnd { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal AdditionalSeatFeeVnd { get; set; }

        [Required]
        [StringLength(50)]
        public string Status { get; set; } = "draft"; // "paid", "upcoming", "overdue", "draft"

        [StringLength(20)]
        public string? PaymentSource { get; set; }

        [StringLength(200)]
        public string? PaymentGatewayRef { get; set; }

        public DateTime IssuedAt { get; set; }

        public DateTime DueAt { get; set; }

        public DateTime AutoGeneratedAt { get; set; } = DateTime.UtcNow;

        public int DraftLeadDays { get; set; } = 7;

        public DateTime? EmailSentAt { get; set; }

        public DateTime? ReminderSentAt { get; set; }

        public DateTime? PaidAt { get; set; }

        public DateTime? ReceivedAt { get; set; }

        public int GracePeriodDays { get; set; } = 7;

        public DateTime? GraceEndsAt { get; set; }

        [StringLength(200)]
        public string PdfFileName { get; set; } = string.Empty;

        [StringLength(500)]
        public string? SummaryNote { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime? UpdatedAt { get; set; }

        [ForeignKey("TenantId")]
        public Tenants? Tenant { get; set; }
    }
}
