using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ERP.Entities.Migrations
{
    /// <inheritdoc />
    public partial class SyncPendingChanges_20260418 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "subdomain",
                table: "Tenants",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ActivatedAt",
                table: "Sys_SupportAccessGrants",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "LastNotifiedAt",
                table: "Sys_SupportAccessGrants",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "RequestedBy",
                table: "Sys_SupportAccessGrants",
                type: "nvarchar(150)",
                maxLength: 150,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "RequestedDurationHours",
                table: "Sys_SupportAccessGrants",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<DateTime>(
                name: "RevokedAt",
                table: "Sys_SupportAccessGrants",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Description",
                table: "Sys_SubscriptionPlans",
                type: "nvarchar(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<decimal>(
                name: "AdditionalSeatFeeVnd",
                table: "Sys_InvoiceMetadata",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<DateTime>(
                name: "AutoGeneratedAt",
                table: "Sys_InvoiceMetadata",
                type: "datetime2",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<decimal>(
                name: "BaseAmountVnd",
                table: "Sys_InvoiceMetadata",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<string>(
                name: "BillingCycle",
                table: "Sys_InvoiceMetadata",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<decimal>(
                name: "DiscountVnd",
                table: "Sys_InvoiceMetadata",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<int>(
                name: "DraftLeadDays",
                table: "Sys_InvoiceMetadata",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<DateTime>(
                name: "EmailSentAt",
                table: "Sys_InvoiceMetadata",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "GraceEndsAt",
                table: "Sys_InvoiceMetadata",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "GracePeriodDays",
                table: "Sys_InvoiceMetadata",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<DateTime>(
                name: "PaidAt",
                table: "Sys_InvoiceMetadata",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "PaymentSource",
                table: "Sys_InvoiceMetadata",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "PdfFileName",
                table: "Sys_InvoiceMetadata",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<DateTime>(
                name: "ReceivedAt",
                table: "Sys_InvoiceMetadata",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ReminderSentAt",
                table: "Sys_InvoiceMetadata",
                type: "datetime2",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "subdomain",
                table: "Tenants");

            migrationBuilder.DropColumn(
                name: "ActivatedAt",
                table: "Sys_SupportAccessGrants");

            migrationBuilder.DropColumn(
                name: "LastNotifiedAt",
                table: "Sys_SupportAccessGrants");

            migrationBuilder.DropColumn(
                name: "RequestedBy",
                table: "Sys_SupportAccessGrants");

            migrationBuilder.DropColumn(
                name: "RequestedDurationHours",
                table: "Sys_SupportAccessGrants");

            migrationBuilder.DropColumn(
                name: "RevokedAt",
                table: "Sys_SupportAccessGrants");

            migrationBuilder.DropColumn(
                name: "Description",
                table: "Sys_SubscriptionPlans");

            migrationBuilder.DropColumn(
                name: "AdditionalSeatFeeVnd",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "AutoGeneratedAt",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "BaseAmountVnd",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "BillingCycle",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "DiscountVnd",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "DraftLeadDays",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "EmailSentAt",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "GraceEndsAt",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "GracePeriodDays",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "PaidAt",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "PaymentSource",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "PdfFileName",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "ReceivedAt",
                table: "Sys_InvoiceMetadata");

            migrationBuilder.DropColumn(
                name: "ReminderSentAt",
                table: "Sys_InvoiceMetadata");
        }
    }
}
